DOXY_BTL:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.SpikeCheck
    threshold_high: 1.0
    threshold_low: 0.4
NTOT:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.SpikeCheck
    threshold_high: 10
    threshold_low: 5