DOXY_BTL:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.SpikeCheck
    threshold_high: 3 # spikes over this are flag 4
    threshold_low: 1 # spikes over this are flag 3
    rate_of_change: 0.1 # max allowed conc change per m to perform test
NTOT:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.SpikeCheck
    threshold_high: 15 # spikes over this are flag 4
    threshold_low: 10 # spikes over this are flag 3
    rate_of_change: 20 # max allowed conc change per m to perform test